name: expirefly

options:
  bundleIdPrefix: com.supergamer474
configs:
  Release: release

targets:
  expirefly:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/expirefly]
    bundleId: com.supergamer474.expirefly
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "Expirefly"
        CFBundleName: "expirefly"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.1.0"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"