name: expirefly

packages:
  skip:
    url: https://source.skip.tools/skip.git
    from: 1.6.18
  skip-fuse:
    url: https://source.skip.tools/skip-fuse.git
    from: 1.0.2
  skip-fuse-ui:
    url: https://source.skip.tools/skip-fuse-ui.git
    from: 1.10.0

options:
  bundleIdPrefix: com.supergamer474
configs:
  Release: release

targets:
  expirefly:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/expirefly]
    bundleId: com.supergamer474.expirefly
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    dependencies:
      - package: skip-fuse-ui/SkipFuseUI
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "Expirefly"
        CFBundleName: "expirefly"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.1.1"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"